# Generated by Django 5.1.4 on 2024-12-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mecanicien', '0001_initial'),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('besoins', models.TextField()),
                ('etat', models.BooleanField()),
                ('confirmer', models.BooleanField()),
                ('date', models.DateField()),
                ('heure', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('cout', models.FloatField()),
                ('idMecanicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanicien.mecanicien')),
                ('idVehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.vehicule')),
            ],
        ),
    ]
