# Generated by Django 5.1.4 on 2024-12-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='estPayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='confirmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='cout',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='duree',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
