# Generated by Django 5.1.4 on 2024-12-23 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanicien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
