# Generated by Django 5.1.4 on 2024-12-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField()),
                ('modele', models.CharField(max_length=50)),
                ('fabricant', models.CharField(max_length=50)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
